### ISSUE TITLE
scene::SceneStack is drawing more than just the last scene

### ISSUE THREAD

**Issue by AlleyShairu** [ggez/ggez-goodies#12]
Hello, I was playing with your Ludum Dare 42 entry, so that I can get familiar with the ggez framework. After skimming the code, I decided to add a simple pause screen, and I was able to achieve this task easily.

**Issue:**
I get strange behavior when I push a new LevelScene again. It should be rendering the last available scene on the stack, but it looks like it's redrawing every LevelScene present in the stack.

```
    level.rs
    if self.done {
        let pause_scene = pause::PauseScene::new();
        scene::SceneSwitch::Push(Box::new(pause_scene))
    }
```
```
   pause.rs
    if self.done {
        // this works fine
        scene::SceneSwitch::Pop

        // but on using this I can see the rendering from the old LevelScene draw method.
        let level = level::LevelScene::new(ctx, gameworld).unwrap();
        scene::SceneSwitch::Push(Box::new(level))
    }

```
Here you can I have total 7 scenes, this is right because I am not popping anything, but why is it rendering every LevelScene entry available in the stack. This doesn't happen for pause scene even if I don't pop them.

![screenshot at 2018-08-25 17 38 05](https://user-images.githubusercontent.com/6375481/44618591-60f28c00-a892-11e8-94c0-eb8ec1530351.png)

The reason I am doing it is because I wanted to see the behavior after adding the ggez::Context to the update method (issue #11 ).

Am I missing something? Please let me know if you have another questions.

**Comment by icefoxen** [comment]
That's odd.  [There is functionality for this](https://github.com/ggez/ggez-goodies/blob/master/src/scene.rs#L37-L42) but it isn't used in my LD game so it should only ever draw the top scene.  I don't see any bugs in [the code that does the actual drawing](https://github.com/ggez/ggez-goodies/blob/master/src/scene.rs#L134-L148) either.  This is pretty mysterious.

**Comment by AlleyShairu** [comment]
@icefoxen I believe, specs is the cause of this behavior. The is only happening because of code present [here](https://github.com/icefoxen/ld42/blob/master/src/scenes/level.rs#L518-L545). I am no specs expert, but I believe the entities we create still exists in the world, and that's why these entities are rendered again.

This also explains why this behavior doesn't happens on the pause screen or why [velocity](https://github.com/icefoxen/ld42/blob/master/src/scenes/level.rs#L560-L561) value is not rendered again. You can emulate this behavior by calling the [create_player](https://github.com/icefoxen/ld42/blob/master/src/scenes/level.rs#L62) method twice. Please correct me if I am wrong.

**Comment by icefoxen** [comment]
Aha! It sounds like you've hit the nail on the head.  The entities are created when the scene loads and the specs World object stores them outside the scene.
