### ISSUE TITLE
Update scene example

### ISSUE THREAD

**Issue by TatriX** [ggez/ggez-goodies#5]
It doesn't look, well, working now.

**Comment by icefoxen** [comment]
Yeah, ggez-goodies on the whole is a lot of stuff I put together as I need it.  :-/

**Comment by icefoxen** [comment]
Right now I'm really focussed on trying to get ggez 0.4 out; that's probably what broke the scene code, since the EventHandler trait has changed a bit.

**Comment by TatriX** [comment]
Nevermind, it's not that important ;)
